// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SudokuApi.Context;

#nullable disable

namespace Sudoku.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20241111200138_NombreMigracionSudoku")]
    partial class NombreMigracionSudoku
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SudokuApi.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoTablero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SudokuID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TiempoInicio")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("TiempoResolucion")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SudokuID");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("SudokuApi.Models.Sudokus", b =>
                {
                    b.Property<int>("SudokuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SudokuID"));

                    b.Property<string>("Solucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tablero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SudokuID");

                    b.ToTable("Sudoku");
                });

            modelBuilder.Entity("SudokuApi.Models.Partida", b =>
                {
                    b.HasOne("SudokuApi.Models.Sudokus", "Sudoku")
                        .WithMany("Partidas")
                        .HasForeignKey("SudokuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sudoku");
                });

            modelBuilder.Entity("SudokuApi.Models.Sudokus", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
